---
## Default Logstash configuration from Logstash base image.
## https://github.com/elastic/logstash/blob/main/docker/data/logstash/config/logstash-full.yml
#
http.host: 128.110.217.133

node.name: logstash

input:
  kafka:
    bootstrap_servers: "128.110.217.157:9092"
    topics: "filebeat"
    group_id: "logstash"
    codec: json

output:
  elasticsearch:
    hosts: ["http://128.110.217.133:9200"]
    index: "logstash-%{+YYYY.MM.dd}"